version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8003:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mongodb
    environment:
      DB_CONNECTION: mongodb
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_DATABASE: task_manager
      DB_USERNAME: task_manager_user
      DB_PASSWORD: 321manager321

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27010:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
