version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8003:8000"
        volumes:
            - .:/var/www/html
            - vite-build:/var/www/html/public/build
        depends_on:
            - mongodb
        environment:
            DB_CONNECTION: mongodb
            DB_HOST: mongodb
            DB_PORT: 27017
            DB_DATABASE: task_manager
            DB_USERNAME: task_manager_user
            DB_PASSWORD: 321manager321

    mongodb:
        image: mongo:6.0
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: task_manager_user
            MONGO_INITDB_ROOT_PASSWORD: 321manager321
            MONGO_INITDB_DATABASE: task_manager
        ports:
            - "27010:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
    vite-build:
